"""AIGER and Graphviz export.

The AIGER file can be checked independently with ABC
(`read_aiger miter.aag; sat`), which is stronger evidence than our own tests.
The DOT output draws the AIG and BDD for figures.
"""

from .aig import FALSE, TRUE, node_of, is_inverted


# AIGER (ASCII variant, .aag)

def write_aiger(aig, roots, path, input_names=None, output_names=None):
    """Write the cone of `roots` as ASCII AIGER.

    Same literal convention as our AIG, but variables must be contiguous with
    inputs first, so nodes are renumbered on the way out.
    """
    cone = aig.cone(roots)
    and_nodes = [n for n in cone if n in aig.and_gates]

    remap = {0: 0}
    next_var = 1
    for node in aig.inputs:
        remap[node] = next_var
        next_var += 1
    for node in and_nodes:
        remap[node] = next_var
        next_var += 1

    def out_lit(lit):
        if lit == FALSE:
            return 0
        if lit == TRUE:
            return 1
        return (remap[node_of(lit)] << 1) | (1 if is_inverted(lit) else 0)

    max_var = next_var - 1
    lines = ["aag %d %d 0 %d %d"
             % (max_var, len(aig.inputs), len(roots), len(and_nodes))]
    for node in aig.inputs:
        lines.append(str(remap[node] << 1))
    for root in roots:
        lines.append(str(out_lit(root)))
    for node in and_nodes:
        a, b = aig.and_gates[node]
        lines.append("%d %d %d" % (remap[node] << 1, out_lit(a), out_lit(b)))

    # Optional symbol table - makes the file readable and lets ABC report
    # meaningful names.
    for index, node in enumerate(aig.inputs):
        name = (input_names or {}).get(node) or aig.input_names.get(node)
        if name:
            lines.append("i%d %s" % (index, name))
    for index, _ in enumerate(roots):
        name = (output_names or [None] * len(roots))[index]
        if name:
            lines.append("o%d %s" % (index, name))

    lines.append("c")
    lines.append("Generated by eqcheck - combinational equivalence checker")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    return {"max_var": max_var, "inputs": len(aig.inputs),
            "ands": len(and_nodes), "outputs": len(roots)}


# Graphviz

def write_aig_dot(aig, roots, path, max_nodes=400, root_labels=None):
    """Draw the AIG. Inverted edges are dashed, matching the usual convention."""
    cone = aig.cone(roots)
    if len(cone) > max_nodes:
        raise ValueError(
            "cone has %d nodes, above the %d-node drawing limit; pick a "
            "smaller design or raise max_nodes" % (len(cone), max_nodes))

    lines = ["digraph aig {", "  rankdir=BT;", "  node [fontname=\"monospace\"];"]
    inputs = set(aig.inputs)

    for node in cone:
        if node in inputs:
            lines.append('  n%d [shape=box, style=filled, fillcolor="#dbeafe", '
                         'label="%s"];' % (node, aig.input_names.get(node, "i%d" % node)))
        elif node in aig.and_gates:
            lines.append('  n%d [shape=circle, label="&"];' % node)

    for node in cone:
        gate = aig.and_gates.get(node)
        if gate is None:
            continue
        for child in gate:
            child_node = node_of(child)
            if child == FALSE or child == TRUE:
                continue
            style = "dashed" if is_inverted(child) else "solid"
            lines.append('  n%d -> n%d [style=%s];' % (child_node, node, style))

    for index, root in enumerate(roots):
        label = (root_labels or [])[index] if root_labels and index < len(root_labels) \
            else "out%d" % index
        lines.append('  o%d [shape=doubleoctagon, style=filled, '
                     'fillcolor="#fecaca", label="%s"];' % (index, label))
        if root in (FALSE, TRUE):
            lines.append('  c%d [shape=plaintext, label="%s"];'
                         % (index, "0" if root == FALSE else "1"))
            lines.append('  c%d -> o%d;' % (index, index))
        else:
            style = "dashed" if is_inverted(root) else "solid"
            lines.append('  n%d -> o%d [style=%s];' % (node_of(root), index, style))

    lines.append("}")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    return len(cone)


def write_bdd_dot(manager, root, path, var_names=None, max_nodes=400):
    """Draw a BDD. Low (0) edges dashed, high (1) edges solid."""
    seen = set()
    stack = [root]
    while stack:
        node = stack.pop()
        if node in seen or node <= 1:
            continue
        seen.add(node)
        _, low, high = manager.nodes[node]
        stack.extend((low, high))

    if len(seen) > max_nodes:
        raise ValueError("BDD has %d nodes, above the %d-node drawing limit"
                         % (len(seen), max_nodes))

    lines = ["digraph bdd {", "  node [fontname=\"monospace\"];"]
    lines.append('  t0 [shape=box, label="0"];')
    lines.append('  t1 [shape=box, label="1"];')

    def ref(node):
        return "t%d" % node if node <= 1 else "n%d" % node

    for node in sorted(seen):
        level, low, high = manager.nodes[node]
        label = (var_names or {}).get(level, "x%d" % level)
        lines.append('  n%d [shape=circle, label="%s"];' % (node, label))
        lines.append('  n%d -> %s [style=dashed];' % (node, ref(low)))
        lines.append('  n%d -> %s [style=solid];' % (node, ref(high)))

    lines.append('  root [shape=plaintext, label="miter"];')
    lines.append('  root -> %s;' % ref(root))
    lines.append("}")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    return len(seen)
