"""Generate the result figures in results/figures/.

Needs matplotlib, which the checker itself does not:

    pip install matplotlib
    python make_plots.py

Data comes from results/figdata.json, regenerated by `python make_plots.py
--measure` (that takes a few minutes; the recorded width-12 SAT runtimes are
kept as constants because those runs took hours).
"""

import argparse
import json
import pathlib
import sys
import time

from eqcheck.bigstack import run as run_big_stack

OUT = pathlib.Path("results/figures")
DATA = pathlib.Path("results/figdata.json")

# Validated categorical slots (light surface #fcfcfb).
BLUE, ORANGE, AQUA, YELLOW = "#2a78d6", "#eb6834", "#1baf7a", "#eda100"
SURFACE = "#fcfcfb"
INK = "#0b0b0b"
INK_2 = "#52514e"
GRID = "#e3e2de"

BDD_LIMIT = 400_000

# Measured separately; each of these took hours, so they are not re-run.
SAT_W12 = 11509.4
SWEEP_W12 = 3227.3


def style(plt):
    plt.rcParams.update({
        "figure.facecolor": SURFACE,
        "axes.facecolor": SURFACE,
        "savefig.facecolor": SURFACE,
        "axes.edgecolor": GRID,
        "axes.labelcolor": INK_2,
        "text.color": INK,
        "xtick.color": INK_2,
        "ytick.color": INK_2,
        "grid.color": GRID,
        "font.size": 9,
        "axes.titlesize": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "legend.frameon": False,
    })


def fig_scaling(data, plt):
    """Multiplier width against proof time, and against BDD size.

    Two panels rather than two y-axes: seconds and node counts are different
    units and must not share a scale.
    """
    rows = data["mult_scaling"]
    alg = data["algebraic"]

    fig, (ax, ax2) = plt.subplots(1, 2, figsize=(10, 4.0))

    w = [r["width"] for r in rows]
    sat = [r["sat"] for r in rows]
    sweep = [r["sweep"] for r in rows]

    ax.plot(w + [12], sat + [SAT_W12], "-o", color=BLUE, lw=2, ms=5,
            label="plain SAT miter")
    ax.plot(w + [12], sweep + [SWEEP_W12], "-o", color=ORANGE, lw=2, ms=5,
            label="SAT + sweeping")
    ax.plot([a["width"] for a in alg], [a["time"] for a in alg], "-o",
            color=AQUA, lw=2, ms=5, label="algebraic")

    ax.set_yscale("log")
    ax.set_xscale("log")
    ax.set_xticks([3, 4, 6, 8, 12, 16, 24, 32, 48, 64])
    ax.get_xaxis().set_major_formatter(plt.matplotlib.ticker.ScalarFormatter())
    ax.set_xlim(2.6, 110)
    ax.set_xlabel("multiplier width (bits, log scale)")
    ax.set_ylabel("proof time (s, log scale)")
    ax.set_title("Proving an N×N multiplier equivalent", loc="left", color=INK)
    ax.grid(axis="y", lw=0.6)
    ax.set_axisbelow(True)
    ax.legend(loc="lower right")

    # Direct labels on the points that carry the story.
    ax.annotate("11,509 s (3 h 12 m)", xy=(12, SAT_W12), xytext=(8, -3),
                textcoords="offset points", ha="left", color=INK_2, fontsize=8)
    ax.annotate("3,227 s", xy=(12, SWEEP_W12), xytext=(8, -11),
                textcoords="offset points", ha="left", color=INK_2, fontsize=8)
    ax.annotate("0.034 s", xy=(12, 0.034), xytext=(-4, -15),
                textcoords="offset points", ha="right", color=INK_2, fontsize=8)
    ax.annotate("64x64 in 7.6 s", xy=(64, 7.639), xytext=(-4, 12),
                textcoords="offset points", ha="right", color=INK_2, fontsize=8)

    peaks = [(r["width"], r["bdd_peak"]) for r in rows if r["bdd_peak"]]
    ax2.plot([p[0] for p in peaks], [p[1] for p in peaks], "-o", color=BLUE,
             lw=2, ms=5)
    ax2.axhline(BDD_LIMIT, color=INK_2, lw=1, ls=":")
    ax2.annotate("400,000-node budget", xy=(3.2, BDD_LIMIT), xytext=(0, 5),
                 textcoords="offset points", color=INK_2, fontsize=8)

    failed = [r["width"] for r in rows if not r["bdd_peak"]]
    for width in failed:
        ax2.plot([width], [BDD_LIMIT], "x", color=INK_2, ms=9, mew=2)
        ax2.annotate("aborted", xy=(width, BDD_LIMIT), xytext=(0, -16),
                     textcoords="offset points", ha="center", color=INK_2,
                     fontsize=8)

    ax2.set_yscale("log")
    ax2.set_xlabel("multiplier width (bits)")
    ax2.set_ylabel("BDD peak nodes (log scale)")
    ax2.set_title("BDD size for the same miters", loc="left", color=INK)
    ax2.grid(axis="y", lw=0.6)
    ax2.set_axisbelow(True)

    fig.tight_layout()
    path = OUT / "scaling.png"
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def fig_ordering(data, plt):
    """Peak BDD nodes per design under each static variable order."""
    import numpy as np

    rows = data["ordering"]
    strategies = [("interleaved", BLUE), ("dfs", ORANGE),
                  ("declaration", AQUA), ("reverse", YELLOW)]

    fig, ax = plt.subplots(figsize=(10, 4.6))
    x = np.arange(len(rows))
    width = 0.2

    for i, (name, colour) in enumerate(strategies):
        offset = (i - 1.5) * width
        values, labels = [], []
        for r in rows:
            v = r[name]
            values.append(v if v else BDD_LIMIT)
            labels.append(None if v else "overflow")
        bars = ax.bar(x + offset, values, width * 0.9, color=colour,
                      edgecolor=SURFACE, linewidth=1.2)
        for bar, lab, v in zip(bars, labels, values):
            if lab:                       # hatch the ones that never finished
                bar.set_hatch("///")
                bar.set_alpha(0.35)
                ax.annotate("overflow", xy=(bar.get_x() + bar.get_width() / 2, v),
                            xytext=(0, 3), textcoords="offset points",
                            rotation=90, ha="center", va="bottom",
                            color=INK_2, fontsize=7)

    # Direct-label the winner of each group.
    for i, r in enumerate(rows):
        best = min(((r[s], s) for s, _ in strategies if r[s]), default=None)
        if best:
            value, name = best
            idx = [s for s, _ in strategies].index(name)
            ax.annotate("%s" % f"{value:,}",
                        xy=(x[i] + (idx - 1.5) * width, value),
                        xytext=(0, 3), textcoords="offset points",
                        ha="center", color=INK, fontsize=7.5, weight="bold")

    ax.set_yscale("log")
    ax.set_xticks(x)
    ax.set_xticklabels([r["design"] for r in rows], fontsize=8.5)
    ax.set_ylabel("BDD peak nodes (log scale)")
    ax.set_title("No variable-ordering heuristic wins everywhere  "
                 "(lower is better; bold = best for that design)",
                 loc="left", color=INK)
    ax.grid(axis="y", lw=0.6)
    ax.set_axisbelow(True)
    # Build the legend from clean solid patches. Taking it from the bars picks
    # up the hatch and alpha of whichever bar overflowed, which would suggest
    # those orders always overflow.
    handles = [plt.matplotlib.patches.Patch(facecolor=c, label=n)
               for n, c in strategies]
    ax.legend(handles=handles, ncol=4, loc="upper center",
              bbox_to_anchor=(0.5, -0.13))
    ax.set_ylim(top=BDD_LIMIT * 3.2)

    fig.tight_layout()
    path = OUT / "bdd_ordering.png"
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def fig_complexity(data, plt):
    """Miter size per test case, as evidence for the complexity requirement."""
    rows = sorted(data["complexity"], key=lambda r: r["gates"])

    fig, ax = plt.subplots(figsize=(9, 5.2))
    y = range(len(rows))
    gates = [r["gates"] for r in rows]

    ax.barh(list(y), gates, height=0.62, color=BLUE, edgecolor=SURFACE,
            linewidth=1.2)
    ax.set_yticks(list(y))
    ax.set_yticklabels([r["design"] for r in rows], fontsize=8.5)
    ax.set_xscale("log")
    ax.set_xlabel("miter gates, after structural hashing (log scale)")
    ax.set_title("Test-case size  (label: primary inputs, so input space is 2^n)",
                 loc="left", color=INK)
    ax.grid(axis="x", lw=0.6)
    ax.set_axisbelow(True)

    for i, r in enumerate(rows):
        ax.annotate("%d gates · %d inputs" % (r["gates"], r["inputs"]),
                    xy=(r["gates"], i), xytext=(6, 0),
                    textcoords="offset points", va="center",
                    color=INK_2, fontsize=7.5)

    ax.set_xlim(right=max(gates) * 6)
    fig.tight_layout()
    path = OUT / "complexity.png"
    fig.savefig(path, dpi=200)
    plt.close(fig)
    return path


def measure():
    """Re-run every measurement the figures need."""
    from eqcheck.equiv import (build_miter, check_sat, check_bdd,
                               best_static_order, variable_order)
    from eqcheck.aig import tseitin
    from eqcheck.algebraic import verify_multiplier

    out = {"mult_scaling": [], "algebraic": [], "ordering": [], "complexity": []}

    for w in range(3, 10):
        m = build_miter("tests/mult_behav.v", "tests/mult_csa.v",
                        param_overrides={"WIDTH": w})
        sat = check_sat(m, presimulate=False)
        m2 = build_miter("tests/mult_behav.v", "tests/mult_csa.v",
                         param_overrides={"WIDTH": w})
        t0 = time.perf_counter()
        check_sat(m2, sweep=True, presimulate=False)
        sweep_t = time.perf_counter() - t0
        search = best_static_order(m, node_limit=BDD_LIMIT)
        bdd = check_bdd(m, order=search["order"], node_limit=BDD_LIMIT)
        peak = None if bdd["aborted"] or search["order"] is None else bdd["peak_nodes"]
        out["mult_scaling"].append({"width": w, "sat": sat["solve_time"],
                                    "sweep": sweep_t, "bdd_peak": peak})
        print("  mult w=%d" % w, flush=True)

    for w in [3, 4, 5, 6, 7, 8, 9, 12, 16, 24, 32, 48, 64]:
        r = verify_multiplier(path="tests/mult_csa.v", params={"WIDTH": w})
        out["algebraic"].append({"width": w, "time": r["time"],
                                 "gates": r["gates"],
                                 "peak_terms": r["peak_terms"]})
        print("  algebraic w=%d" % w, flush=True)

    cases = [("16-bit RCA vs CLA", "adder16_rca.v", "adder16_cla.v", None),
             ("16-bit RCA vs KS", "adder16_rca.v", "adder16_ks.v", None),
             ("8-bit ALU", "alu8_behav.v", "alu8_struct.v", None),
             ("8-bit shifter", "barrel8_behav.v", "barrel8_crossbar.v", None),
             ("popcount", "popcount8_seq.v", "popcount8_tree.v", None),
             ("6x6 multiplier", "mult_behav.v", "mult_csa.v", {"WIDTH": 6})]
    for label, spec, impl, params in cases:
        m = build_miter("tests/" + spec, "tests/" + impl,
                        param_overrides=params or {})
        entry = {"design": label}
        for strat in ("interleaved", "dfs", "declaration", "reverse"):
            r = check_bdd(m, order=variable_order(m, strat), node_limit=BDD_LIMIT)
            entry[strat] = None if r["aborted"] else r["peak_nodes"]
        out["ordering"].append(entry)
        print("  ordering", label, flush=True)

    suite = [("128-bit adder", "add_rca.v", "add_csel.v", {"WIDTH": 128}),
             ("64-bit adder", "add_rca.v", "add_csel.v", {"WIDTH": 64}),
             ("32-bit adder", "add_rca.v", "add_csel.v", {"WIDTH": 32}),
             ("12x12 multiplier", "mult_behav.v", "mult_csa.v", {"WIDTH": 12}),
             ("8x8 multiplier", "mult_behav.v", "mult_csa.v", {"WIDTH": 8}),
             ("16-bit RCA vs KS", "adder16_rca.v", "adder16_ks.v", None),
             ("16-bit CLA vs KS", "adder16_cla.v", "adder16_ks.v", None),
             ("16-bit RCA vs CLA", "adder16_rca.v", "adder16_cla.v", None),
             ("8-bit ALU", "alu8_behav.v", "alu8_struct.v", None),
             ("8-bit shifter", "barrel8_behav.v", "barrel8_crossbar.v", None),
             ("popcount", "popcount8_seq.v", "popcount8_tree.v", None),
             ("priority encoder", "prio8_casez.v", "prio8_struct.v", None),
             ("Gray roundtrip", "gray8_roundtrip.v", "gray8_identity.v", None),
             ("ISCAS-85 c17", "c17_gates.v", "c17_table.v", None)]
    for label, spec, impl, params in suite:
        m = build_miter("tests/" + spec, "tests/" + impl,
                        param_overrides=params or {})
        gates = sum(1 for n in m.aig.cone([m.root]) if n in m.aig.and_gates)
        cnf, _v, _d = tseitin(m.aig, [m.root])
        out["complexity"].append({"design": label, "inputs": m.aig.num_inputs,
                                  "gates": gates, "depth": m.aig.depth([m.root]),
                                  "clauses": len(cnf.clauses)})
        print("  complexity", label, flush=True)

    DATA.write_text(json.dumps(out, indent=1), encoding="utf-8")
    print("wrote", DATA)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--measure", action="store_true",
                        help="re-run the measurements before plotting")
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    if args.measure or not DATA.exists():
        measure()

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is required for the plots: pip install matplotlib")
        return 1

    style(plt)
    data = json.loads(DATA.read_text(encoding="utf-8"))
    for fn in (fig_scaling, fig_ordering, fig_complexity):
        print("wrote", fn(data, plt))
    return 0


if __name__ == "__main__":
    sys.exit(run_big_stack(main))
